make ad-blocker script even more universal

diff --git a/res/customconfig/actions/push-actions/ad_update b/res/customconfig/actions/push-actions/ad_update
--- a/res/customconfig/actions/push-actions/ad_update
+++ b/res/customconfig/actions/push-actions/ad_update
@@ -19,7 +19,7 @@ Get_File(){
     $DOS2UNIX -u $HOST_FILE
 	ALL_OK=1
   else
-    $ECHO "Download failed:"
+    $ECHO "Download failed!"
 	if [ -s $ERR_FILE ]
 	then
 	  $CAT $ERR_FILE
@@ -33,9 +33,6 @@ Get_File(){
 # Main()
 ##############################################################################
 
-echo "Ad Blocker"
-echo "----------"
-
 BUSYBOX=""
 # Check if $BUSYBOX has been installed
 for i in /tmp /system/xbin /sbin /system/bin
@@ -48,7 +45,7 @@ do
 done
 if [ ! "$BUSYBOX" ]
 then
-  echo "BusyBox not found!"
+  echo "Ad Blocker: BusyBox not found!"
   exit 1
 fi
 
@@ -60,6 +57,7 @@ ECHO="$BUSYBOX echo"
 GREP="$BUSYBOX grep"
 HEAD="$BUSYBOX head"
 MKTEMP="$BUSYBOX mktemp"
+MOUNT="$BUSYBOX mount"
 if [ -x /system/bin/ping ]
 then
   PING1="/system/bin/ping"
@@ -74,63 +72,46 @@ UNZIP="$BUSYBOX unzip"
 WGET="$BUSYBOX wget"
 # ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 
-mount -o remount,rw /
-mount -o remount,rw /system
+$ECHO "Ad Blocker"
+$ECHO "----------"
+
+$MOUNT -o remount,rw /
+$MOUNT -o remount,rw /system
 
 WGET_FILE=$($MKTEMP -t).zip
 ERR_FILE=$($MKTEMP -t)
 HOST_FILE=/system/etc/hosts
-CONF_FILE=/system/etc/resolv.conf
-
-DNS1=`getprop net.dns1`
-DNS2=`getprop net.rmnet0.dns1`
-DNS3=`getprop net.rmnet0.dns2`
-
-# Set up the dns resolve file
-$ECHO "Configuring DNS resolutions..."
-$ECHO "nameserver 8.8.8.8" > $CONF_FILE
-$ECHO "nameserver 4.4.8.8" >> $CONF_FILE
-for i in $DNS1 $DNS2 $DNS3
-do 
-  if [ "$i" ]
-  then      
-    $ECHO "nameserver $i" >> $CONF_FILE
-  fi
-done
-$CHMOD 644 $CONF_FILE
 
 domain="www.winhelp2002.mvps.org"	
 zip_url="$domain/hosts.zip"
 
-# See if the domain is in the host file
-# If not then temporarily add it
-add_domain=0
-if [ -e $HOST_FILE ]
+# Get this host's ip address
+$ECHO "Resolving $domain..."
+ipaddr=`$PING1 -c 1 $domain | $SED -n 's@^.*(\([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\).*$@\1@p' | $HEAD -1`
+if [ ! "$ipaddr" ] && [ "$PING2" ]
 then
-  $GREP -i $domain $HOST_FILE 1>/dev/null 2>/dev/null
-  if [ $? -ne 0 ]
-  then
-    add_domain=1
-  fi
-else
-  add_domain=1
+  $ECHO "Fallback Ping..."
+  ipaddr=`$PING2 -c 1 $domain | $SED -n 's@^.*(\([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\).*$@\1@p' | $HEAD -1`
 fi
-if [ $add_domain -eq 1 ]
+if [ "$ipaddr" ]
 then
-  # It is not in the host file
-  # Get this host's ip address
-  $ECHO "Ping test: $domain"
-  ipaddr=`$PING1 -c 1 $domain | $SED -n 's@^.*(\([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\).*$@\1@p' | $HEAD -1`
-  if [ ! "$ipaddr" ] && [ "$PING2" ]
+  $ECHO "IP Address: $ipaddr"
+  # IP Address for Ad Blocker domain found
+  # See if the domain is in the host file
+  # If not then temporarily add it
+  add_domain=1
+  if [ -e $HOST_FILE ]
   then
-    $ECHO "Fallback Ping test: $domain"
-    ipaddr=`$PING2 -c 1 $domain | $SED -n 's@^.*(\([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\).*$@\1@p' | $HEAD -1`
+    $GREP -i $domain $HOST_FILE 1>/dev/null 2>/dev/null
+    if [ $? -eq 0 ]
+    then
+      add_domain=0
+    fi
   fi
-  if [ "$ipaddr" ]
+  if [ $add_domain -eq 1 ]
   then
 	# Temporarily add this domain's ip address to the hosts file
-	$ECHO "Adding Ad Blocker domain to hosts:"
-	$ECHO "$ipaddr $domain"
+	# so that the wget command will work properly
 	$ECHO >> $HOST_FILE
 	$ECHO "# $domain added by Ad Blocker vvvvv" >> $HOST_FILE
 	$ECHO "$ipaddr $domain">>$HOST_FILE
@@ -138,16 +119,36 @@ then
 	$SLEEP 1
   fi
 fi
+
+add_nameserver=1
 if [ -e $HOST_FILE ]
 then
   $GREP -i $domain $HOST_FILE 1>/dev/null 2>/dev/null
   if [ $? -eq 0 ]
   then
-    $ECHO "Ad Blocker domain found in hosts"
-  else
-    $ECHO "Unable to obtain IP-Address for $domain"
-	$ECHO "Attempting with DNS resolution"
+    add_nameserver=0
   fi
+fi
+if [ $add_nameserver -eq 1 ]
+then
+  $ECHO "Unknown IP-Address for $domain"
+  $ECHO "Attempting with DNS resolution..."
+  conf_file=/system/etc/resolv.conf
+  dns1=`getprop net.dns1`
+  dns2=`getprop net.rmnet0.dns1`
+  dns3=`getprop net.rmnet0.dns2`
+
+  # Set up the dns resolve file
+  $ECHO "nameserver 8.8.8.8" > $conf_file
+  $ECHO "nameserver 4.4.8.8" >> $conf_file
+  for i in $dns1 $dns2 $dns3
+  do 
+    if [ "$i" ]
+    then      
+      $ECHO "nameserver $i" >> $conf_file
+    fi
+  done
+  $CHMOD 644 $conf_file
 fi
 
 # Attempt to download the hosts.zip file
