scrips update

diff --git a/res/customconfig/actions/push-actions/ad_update b/res/customconfig/actions/push-actions/ad_update
--- a/res/customconfig/actions/push-actions/ad_update
+++ b/res/customconfig/actions/push-actions/ad_update
@@ -40,61 +40,31 @@ do
     break
   fi
 done
+if [ ! "$BUSYBOX" ]
+then
+  echo "BusyBox not found!"
+  exit 1
+fi
 
 # Set all the required the commands with the correct path to busybox
-AWK="$BUSYBOX awk"
-BASENAME="$BUSYBOX basename"
-CAT="$BUSYBOX cat"
 CHMOD="$BUSYBOX chmod"
-CP="$BUSYBOX cp"
-CUT="$BUSYBOX cut"
-DATE="$BUSYBOX date"
-DD="$BUSYBOX dd"
-DF="$BUSYBOX df"
-DIRNAME="$BUSYBOX dirname"
 DOS2UNIX="$BUSYBOX dos2unix"
-DU="$BUSYBOX du"
 ECHO="$BUSYBOX echo"
-EXPR="$BUSYBOX expr"
-FIND="$BUSYBOX find"
 GREP="$BUSYBOX grep"
 HEAD="$BUSYBOX head"
-LS="$BUSYBOX ls"
-LN="$BUSYBOX ln"
-MKDIR="$BUSYBOX mkdir"
 MKTEMP="$BUSYBOX mktemp"
-MOUNT="$BUSYBOX mount"
-MV="$BUSYBOX mv"
-PIDOF="$BUSYBOX pidof"
 if [ -x /system/bin/ping ]
 then
   PING="/system/bin/ping"
 else
   PING="$BUSYBOX ping"
 fi
-PS="$BUSYBOX ps"
-PWD="$BUSYBOX pwd"
-REV="$BUSYBOX rev"
-RM="$BUSYBOX rm"
 SED="$BUSYBOX sed"
 SLEEP="$BUSYBOX sleep"
-TAIL="$BUSYBOX tail"
-TOUCH="$BUSYBOX touch"
-TR="$BUSYBOX tr"
-UNMOUNT="$BUSYBOX unmount"
 UNZIP="$BUSYBOX unzip"
-WC="$BUSYBOX wc"
 WGET="$BUSYBOX wget"
 # ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 
-if [ "$BUSYBOX" ]
-then
-  $ECHO "Busybox: $BUSYBOX"
-else
-  echo "Your BusyBox is not supported"
-  exit 1
-fi
-  
 mount -o remount,rw /
 mount -o remount,rw /system
 
@@ -110,7 +80,7 @@ DNS3=`getprop net.rmnet0.dns2`
 # Set up the dns resolve file
 $ECHO "Configuring DNS resolutions..."
 $ECHO "nameserver 8.8.8.8" > $CONF_FILE
-$ECHO "nameserver 8.8.4.4" >> $CONF_FILE
+$ECHO "nameserver 4.4.8.8" >> $CONF_FILE
 for i in $DNS1 $DNS2 $DNS3
 do 
   if [ "$i" ]
@@ -120,7 +90,6 @@ do
 done
 $CHMOD 644 $CONF_FILE
 
-$RM -f $WGET_FILE 2>/dev/null
 domain="www.winhelp2002.mvps.org"	
 zip_url="$domain/hosts.zip"
 
@@ -147,11 +116,6 @@ then
 	# Temporarily add this domain's ip address to the hosts file
 	$ECHO "Adding Ad Blocker domain to hosts:"
 	$ECHO "$ipaddr $domain"
-	$RM -f $HOST_FILE.bak 2>/dev/null
-	if [ -e $HOST_FILE ]
-	then
-	  $CP $HOST_FILE $HOST_FILE.bak
-	fi
 	$ECHO >> $HOST_FILE
 	$ECHO "# $domain added by Ad Blocker vvvvv" >> $HOST_FILE
 	$ECHO "$ipaddr $domain">>$HOST_FILE
@@ -164,25 +128,28 @@ then
   $GREP -i $domain $HOST_FILE 1>/dev/null 2>/dev/null
   if [ $? -eq 0 ]
   then
-    # Its now in the host file
-    # Attempt a wget
-    Get_File $zip_url
+    $ECHO "Ad Blocker domain added to hosts"
   else
     $ECHO "Unable to obtain IP-Address for $domain"
+	$ECHO "Attempting with DNS resolution"
   fi
-else
-  $ECHO "Unable to find $HOST_FILE"
 fi
-$RM -f $HOST_FILE.bak 2>/dev/null
+
+# Attempt to download the hosts.zip file
+Get_File $zip_url
 
 if [ $ALL_OK -eq 1 ]
 then
   $ECHO "Installed new $HOST_FILE"
   $ECHO "Reboot to apply."
+  exit_val=0
 else
-  $ECHO "No internet connection"
+  $ECHO "Unable to download Ad Blocker hosts file"
   $ECHO "Please try again!"
+  exit_val=1
 fi
 
 $RM -f $WGET_FILE 2>/dev/null
 $RM -f $ERR_FILE 2>/dev/null
+
+exit $exit_val
